CREATE DATABASE taller_veterinaria;

CREATE TABLE Duenos (
ID INT PRIMARY KEY AUTO_INCREMENT,
Cedula VARCHAR(50) UNIQUE NOT NULL,
nombre VARCHAR(100) NOT NULL,
telefono VARCHAR(50),
direccion VARCHAR(50)
);

CREATE TABLE Veterinario (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR (150),
Cedula VARCHAR(50) UNIQUE NOT NULL
);


CREATE TABLE Mascotas (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_Duenos INT NOT NULL,
nombre VARCHAR(200) NOT NULL,
especie VARCHAR(150),
raza VARCHAR(150),
edad INT,
sexo VARCHAR(20),
vacunado BOOLEAN,
FOREIGN KEY (ID_Duenos) REFERENCES Duenos(ID)
);

CREATE TABLE Servicios (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR(150) NOT NULL,
descripcion VARCHAR(200),
precio INT
);

CREATE TABLE Visitas (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
fecha DATE,
ID_Servicios INT NOT NULL,
ID_Mascotas INT NOT NULL,
ID_Veterinario INT NOT NULL,
FOREIGN KEY (ID_Servicios) REFERENCES Servicios(ID),
FOREIGN KEY (ID_Mascotas) REFERENCES Mascotas(ID),
FOREIGN KEY (ID_Veterinario) REFERENCES Veterinario(ID)
);


CREATE TABLE Tratamientos (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_Visitas INT NOT NULL,
ID_Veterinario INT NOT NULL,
nombre VARCHAR(100) NOT NULL,
observacion VARCHAR(150),
FOREIGN KEY (ID_Visitas) REFERENCES Visitas(ID),
FOREIGN KEY (ID_Veterinario) REFERENCES Veterinario(ID)
);


